version: "{build}"

platform: 
  - x64
  - x86

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - git config --global user.name "Eko Eryanto"
  - git config --global user.email ekoeryanto@gmail.com

matrix:
  fast_finish: true

install:
  - ps: Install-Product node 10 $env:PLATFORM
  - cmd: SET JOBS=4
  - cmd: npm install
  - cmd: npx prebuild --strip -r electron --all -u %PREBUILD_TOKEN%
  - cmd: npx prebuild --strip -r node-webkit --all -u %PREBUILD_TOKEN%
  - cmd: npx prebuild --strip --all -u %PREBUILD_TOKEN%
  # - cmd: npx prebuild-ci
test_script:
  - node --version
  - npm --version

build: off

branches:
  only:
    - appveyor

cache:
  - '%APPDATA%\npm-cache'
  - 'node_modules'